version: '3.8'

name: social-network

services:
  social-network-prod:
    build:
      context: .
      target: production
    container_name: social-network-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend-prod
    networks:
      - social-network

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: social-network-backend-prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres-prod
      - DB_PORT=5432
      - DB_NAME=social_network
      - DB_USER=social_user
      - DB_PASSWORD=social_password
      - JWT_SECRET=your_production_jwt_secret_change_this
    depends_on:
      - postgres-prod
    networks:
      - social-network

  postgres-prod:
    image: postgres:15-alpine
    container_name: social-network-db-prod
    environment:
      - POSTGRES_DB=social_network
      - POSTGRES_USER=social_user
      - POSTGRES_PASSWORD=social_password
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - social-network

networks:
  social-network:
    driver: bridge

volumes:
  postgres_prod_data:
