
name: social-network

services:
  social-network:
    build:
      context: .
      target: development
    container_name: social-network-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_DB_HOST=postgres
      - NEXT_PUBLIC_DB_PORT=5432
      - NEXT_PUBLIC_DB_NAME=social_network
      - NEXT_PUBLIC_DB_USER=social_user
      - NEXT_PUBLIC_DB_PASSWORD=social_password
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    networks:
      - social-network

  postgres:
    image: postgres:15-alpine
    container_name: social-network-db
    environment:
      - POSTGRES_DB=social_network
      - POSTGRES_USER=social_user
      - POSTGRES_PASSWORD=social_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - social-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social-network-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=social_network
      - DB_USER=social_user
      - DB_PASSWORD=social_password
      - JWT_SECRET=your_jwt_secret_key_change_in_production
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - social-network

networks:
  social-network:
    driver: bridge

volumes:
  postgres_data:
